FROM dunglas/frankenphp:latest-php8.3-bookworm

RUN install-php-extensions \
	pdo_pgsql \
	opcache

RUN apt-get update && apt-get install -y \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN php -r "copy('https://getcomposer.org/installer?a=1', 'composer-setup.php');"  \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer  \
    && php -r "unlink('composer-setup.php');"

